# If a tag is pushed to the main branch with the format v#.#.# then build a docker image and push to docker hub

name: Build docker hub image for django website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  create:
#    tag: v[1-9]+\.[0-9]+\.[0-9]+

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MW_DOCKER_USER }}
          password: ${{ secrets.MW_DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
#          tags: ${{ secrets.MW_DOCKER_USER }}/sticks:${{ steps.get_version.outputs.VERSION }}
          tags: v1
          build-args: MW_DJANGO_SECRET_KEY=${{ secrets.MW_DJANGO_SECRET_KEY }}
          username: ${{ secrets.MW_DOCKER_USER }}
          password: ${{ secrets.MW_DOCKER_HUB_ACCESS_TOKEN }}
